### PR TITLE
Stanford Profile Updates 2022-05-10

### PR DESCRIPTION
**Pull request by joegl**
# READY FOR REVIEW

# Summary
- Added twitter card metadata for person content
- Several tweaks to the taxonomy display and fields. (#532)
- Update block.block.minimally_branded_subtheme_pagetitle.yml (#535)
- D8CORE-5772: Added custom block and edit link on `/courses` page (#534)
- D8CORE-5748: Adding a listy style to the taxonomy terms (#533)
- D8CORE-5778: adding the grid col 3 for three across (#530)
- D8CORE-5627: added <object> and <param> to allowed tags in embeddables (#529)
- D8CORE-5729 People term pages: display only child terms groupings (#526)
- D8CORE-5187 Courses and Importer(#500)
- D8CORE-5611 Allow multiple basic page types and change widget
- D8CORE-5696 Only display location address once (#520)
- D8CORE-5629 Adjust profile link url for stanford only profiles (#521)
- D8CORE-4118 Remove layout builder settings on other display modes (#519)
- D8CORE-4128 Change views to HTML lists (#518)
- Enabled transliterate_filenames from stanford_media
- D8CORE-3975 Created shared tags vocabulary and fields (#511)
- D8CORE-5666 Enabled and configured responsive_tables_filter module (#515)
- Dont trim the url on even cards
- Updated link_title_formatter module
- Updated domain_301_redirect version
- D8CORE-5172: Updated references to localist and events-legacy urls
- DO not require lockup option select, prevent requiring lockup fields

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Urgency
- How urgent is this? (Normal, High)

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to...
4. Verify...

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by pookmish** [comment]
YOu probably want to pull from stanford_profile once more. A few additions were added recently.

**Comment by joegl** [comment]
> YOu probably want to pull from stanford_profile once more. A few additions were added recently.

I did this 15 minutes ago so I think I'm good? 😄 

I'm running `git pull https://github.com/SU-SWS/stanford_profile.git main -X ours --no-edit` and it says I'm Already up to date.

**Comment by joegl** [comment]
@pookmish I think this is ready to go, if you want take another quick peek.

**Comment by pookmish** [comment]
I still see some outdated configs. be sure you've pulled the latest code.

**Comment by joegl** [comment]
> I still see some outdated configs. be sure you've pulled the latest code.

Ahh you're right my bad. Didn't see the release yesterday for `stanford_profile`. I will get that in quick.

**Comment by mdyoung3** [comment]
@joegl I'll try again after you get the latest, but I'm getting an error with database updates:

Screen Shot 2022-05-11 at 12 13 52 PM

**Comment by pookmish** [comment]
Marc, you need to have all images downloaded to your local for the database updates to run. The information is in the error:
"File [filepath] does not exist"

**Comment by joegl** [comment]
Yea, the full site sync commands are:

```
blt drupal:sync:private-files --site=trustees
blt drupal:sync:files --site=trustees
blt drupal:sync --site=trustees
```

And make sure you have `files-private` directory setup in your repo root for the private files to go into before running the above (NOT docroot).

**Comment by mdyoung3** [comment]
Hm. Yeah, it works now. I've never seen updates dependent on content before. Thanks!

**Comment by pookmish** [comment]
Updates frequently depend on content. That's what they are updating if not the database tables. This particular one modifies files and so if the database knows of a file, it's expected that file exists.

**Review by pookmish — APPROVED** [review]

**Comment by joegl** [comment]
Alright this should be up to date now. I've got it all running locally.

**Comment by pookmish** [comment]
I set up auto merge, once the tests pass

**Comment by mdyoung3** [comment]
@pookmish Maybe I wasn't clear with 'content' I mean user content. Like the images. I've never had to rsync files from the server before making database updates.

**Comment by pookmish** [comment]
yes, that is what i mean. it's unusual to move files, yes but very often database updates depend on user generated content.

**Comment by mdyoung3** [comment]
User content. Like an editor goes in and adds an image. Creates a new node and what not.  How could that image then become dependent on a database update? This doesn't make sense to me.

**Comment by mdyoung3** [comment]
I guess I figured it's mostly schema updates.

**Comment by joegl** [comment]
> I guess I figured it's mostly schema updates.

Yea, but sometimes (rarely) schema updates change file locations, so the files get moved around. In this case I don't think the issue had to do with not having the files on your local but not having the private file location setup on your local. The update still completed (at least for me) when all files weren't present, although it does throw some errors/warnings.

**Pull request merged**
